const output=[
        {
        'id':0,
        'State_Name':'AndhraPradesh',
        'Crop':'Rice',
        'Production':7330.0
        },
        {
        'id':1,
        'State_Name':'Assam',
        'Crop':'Rice',
        'Production':4900.3
        
        },
        {
        'id':2,
        'State_Name':'Bihar',
        'Crop':'Rice',
        'Production':5900.2
        }, 
        {
        'id':3,
        'State_Name':'Chattisgarh',
        'Crop':'Rice',
        'Production':6340.6
        },           
        {
        'id':4,
        'State_Name':'Gujarat',
        'Crop':'Rice',
        'Production':1634.2
        },
        {
        'id':5,
        'State_Name':'Haryana',
        'Crop':'Rice',
        'Production':3800.2
        },
        {
        'id':6,
        'State_Name':'HimachalPradesh',
        'Crop':'Rice',
        'Production':120.3
        }, 
        {
        'id':7,
        'State_Name':'JammuKashmir',
        'Crop':'Rice',
        'Production':530.1
        },           
        {   
        'id':8,
        'State_Name':'Jharkhand',
        'Crop':'Rice',
        'Production':2802.5
        },
        {
        'id':9,
        'State_Name':'Karnataka',
        'Crop':'Rice',
        'Production':3724.1
        },
        {
        'id':10,
        'State_Name':'Kerala',
        'Crop':'Rice',
        'Production':602.3
        }, 
        {
        'id':11,
        'State_Name':'MadhyaPradesh',
        'Crop':'Rice',
        'Production':2634.6
        },           
        {
        'id':12,
        'State_Name':'Maharastra',
        'Crop':'Rice',
        'Production':3004.8
        },
        {
        'id':13,
        'State_Name':'Orissa',
        'Crop':'Rice',
        'Production':7404.9
        },
        {
        'id':14,
        'State_Name':'Punjab',
        'Crop':'Rice',
        'Production':11025.4
        }, 
        {
        'id':15,
        'State_Name':'Rajasthan',
        'Crop':'Rice',
        'Production':234.1
        },           
        {
        'id':16,
        'State_Name':'Tamilnadu',
        'Crop':'Rice',
        'Production':5467.3
        
            },
            {
        'id':17,
        'State_Name':'Telengana',
        'Crop':'Rice',
        'Production':5235.6
        
            },
{
        'id':18,
        'State_Name':'UttarPradesh',
        'Crop':'Rice',
        'Production':13423.8
        
            }, 
{
        'id':19,
        'State_Name':'Uttarkhand',
        'Crop':'Rice',
        'Production':540.2
        
            },           
{
        'id':20,
        'State_Name':'WestBengal',
        'Crop':'Rice',
        'Production':'14512.5'
        
            },
        {
        'id':21,
        'State_Name':'Overall',
        'Crop':'Rice',
        'Production':103231.6
        
            },

    ]
    export default output;